import type { TimedLyric } from './LyricsManager';

const lyrics: TimedLyric[] = [
  { start: 11, text: 'Hark! The herald' },
  { start: 14, text: 'angels sing' },
  { start: 16, text: 'Glory to the' },
  { start: 18, text: 'new-born King' },
  { start: 20, text: 'Peace on earth' },
  { start: 23, text: 'and mercy mild' },
  { start: 25, text: 'God and sinners' },
  { start: 27, text: 'reconciled' },
  { start: 29, text: 'Joyful all ye' },
  { start: 32, text: 'nations rise' },
  { start: 34, text: 'Join the triumph' },
  { start: 36, text: 'of the skies' },
  { start: 38, text: 'With angelic host' },
  { start: 41, text: 'proclaim' },
  { start: 43, text: 'Christ is born in' },
  { start: 45, text: 'Bethlehem' },
  { start: 47, text: 'Hark! The herald' },
  { start: 49, text: 'angels sing' },
  { start: 51, text: 'Glory to the' },
  { start: 54, text: 'new-born King' },
  { start: 57, text: 'Christ, by highest' },
  { start: 60, text: 'heaven adored' },
  { start: 62, text: 'Christ, the' },
  { start: 64, text: 'everlasting Lord' },
  { start: 66, text: 'Late in time' },
  { start: 69, text: 'behold him come' },
  { start: 71, text: 'Offspring of a' },
  { start: 73, text: 'virgin\'s womb' },
  { start: 75, text: 'Veiled in flesh the' },
  { start: 77, text: 'Godhead see' },
  { start: 79, text: 'Hail the incarnate' },
  { start: 82, text: 'Deity' },
  { start: 84, text: 'Pleased with us in' },
  { start: 86, text: 'flesh to dwell' },
  { start: 88, text: 'Jesus, our' },
  { start: 90, text: 'Immanuel' },
  { start: 93, text: 'Hark! The herald' },
  { start: 95, text: 'angels sing' },
  { start: 97, text: 'Glory to the' },
  { start: 100, text: 'new-born king' },
  { start: 103, text: 'Hail the heaven-born' },
  { start: 105, text: 'Prince of Peace' },
  { start: 107, text: 'Hail the Son of' },
  { start: 110, text: 'Righteousness' },
  { start: 112, text: 'Light and life to' },
  { start: 114, text: 'all He brings' },
  { start: 116, text: 'Risen with healing' },
  { start: 118, text: 'in His wings' },
  { start: 121, text: 'Mild He lays His' },
  { start: 123, text: 'glory by' },
  { start: 125, text: 'Born that man no' },
  { start: 127, text: 'more may die' },
  { start: 130, text: 'Born to raise the' },
  { start: 132, text: 'sons of earth' },
  { start: 134, text: 'Born to give them' },
  { start: 136, text: 'second birth' },
  { start: 139, text: 'Hark! The herald' },
  { start: 141, text: 'angels sing' },
  { start: 143, text: 'Glory to the' },
  { start: 145, text: 'new-born king' }
];

export default lyrics;