import type { TimedLyric } from './LyricsManager';

const lyrics: TimedLyric[] = [
  { start: 12, text: 'Joy to the world;' },
  { start: 15, text: 'the Lord is come;' },
  { start: 18, text: 'Let Earth receive' },
  { start: 20, text: 'her King;' },
  { start: 23, text: 'Let ev\'ry heart' },
  { start: 26, text: 'prepare him room,' },
  { start: 29, text: 'And heav\'n and' },
  { start: 31, text: 'nature sing.' },
  { start: 32, text: 'And heav\'n and' },
  { start: 34, text: 'nature sing.' },
  { start: 35, text: 'And heav\'n, And' },
  { start: 37, text: 'heav\'n and nature' },
  { start: 39, text: 'sing.' },
  { start: 51, text: 'Joy to the Earth,' },
  { start: 54, text: 'the Savior reigns;' },
  { start: 56, text: 'Our mortal songs' },
  { start: 59, text: 'employ,' },
  { start: 62, text: 'While fields and' },
  { start: 64, text: 'floods, rocks, hills' },
  { start: 66, text: 'and plains,' },
  { start: 68, text: 'Repeat the sounding' },
  { start: 70, text: 'joy.' },
  { start: 71, text: 'Repeat the sounding' },
  { start: 73, text: 'joy.' },
  { start: 74, text: 'Repeat, Repeat the' },
  { start: 76, text: 'sounding joy.' },
  { start: 90, text: 'No more let sins' },
  { start: 93, text: 'and sorrows grow,' },
  { start: 95, text: 'Nor thorns infest' },
  { start: 98, text: 'the ground;' },
  { start: 101, text: 'He comes to make' },
  { start: 104, text: 'his blessings flow' },
  { start: 107, text: 'Far as the curse' },
  { start: 109, text: 'is found.' },
  { start: 110, text: 'Far as the curse' },
  { start: 112, text: 'is found.' },
  { start: 112, text: 'Far as, Far as' },
  { start: 114, text: 'the curse is found.' }
];

export default lyrics;