import type { TimedLyric } from './LyricsManager';

const lyrics: TimedLyric[] = [
  { start: 12, text: 'O come, O come,' },
  { start: 16, text: 'Emmanuel' },
  { start: 20, text: 'And ransom captive' },
  { start: 24, text: 'Israel' },
  { start: 28, text: 'That mourns in' },
  { start: 32, text: 'lonely exile here' },
  { start: 36, text: 'Until the Son of' },
  { start: 40, text: 'God appear' },
  { start: 44, text: 'Rejoice, rejoice,' },
  { start: 49, text: 'Emmanuel' },
  { start: 54, text: 'Shall come to thee,' },
  { start: 60, text: 'O Israel' },
  { start: 65, text: 'O come, Thou' },
  { start: 67, text: 'Day-Spring' },
  { start: 68, text: 'Come and cheer' },
  { start: 72, text: 'Thy spirits by Thine' },
  { start: 76, text: 'advent here' },
  { start: 80, text: 'Disperse the gloomy' },
  { start: 84, text: 'clouds of night' },
  { start: 88, text: 'And death\'s dark' },
  { start: 92, text: 'shadows put to flight' },
  { start: 95, text: 'Rejoice, rejoice,' },
  { start: 100, text: 'Emmanuel' },
  { start: 105, text: 'Shall come to thee,' },
  { start: 110, text: 'o Israel' },
  { start: 115, text: 'O come, Thou' },
  { start: 119, text: 'Wisdom from on high' },
  { start: 123, text: 'And order all things,' },
  { start: 127, text: 'far and nigh' },
  { start: 130, text: 'To us the path of' },
  { start: 134, text: 'knowledge show' },
  { start: 137, text: 'And cause us in her' },
  { start: 141, text: 'ways to go' },
  { start: 145, text: 'Rejoice, rejoice,' },
  { start: 150, text: 'Emmanuel' },
  { start: 154, text: 'Shall come to thee,' },
  { start: 160, text: 'o Israel' },
  { start: 165, text: 'O come, Thou Key' },
  { start: 169, text: 'of David, come' },
  { start: 172, text: 'And open wide our' },
  { start: 176, text: 'heavenly home' },
  { start: 180, text: 'Make safe the way' },
  { start: 184, text: 'that leads on high' },
  { start: 187, text: 'And close the path' },
  { start: 191, text: 'to misery' },
  { start: 195, text: 'Rejoice, rejoice,' },
  { start: 200, text: 'Emmanuel' },
  { start: 205, text: 'Shall come to thee,' },
  { start: 210, text: 'o Israel' }
];

export default lyrics;