import type { TimedLyric } from './LyricsManager';

const lyrics: TimedLyric[] = [
  { start: 11, text: 'O come all ye' },
  { start: 15, text: 'faithful, joyful' },
  { start: 18, text: 'and triumphant,' },
  { start: 20, text: 'O come ye, O come' },
  { start: 24, text: 'ye, to Bethlehem.' },
  { start: 29, text: 'Come and behold him,' },
  { start: 34, text: 'born the King of' },
  { start: 36, text: 'angels;' },
  { start: 38, text: 'O come let us' },
  { start: 41, text: 'adore him,' },
  { start: 43, text: 'O come let us' },
  { start: 46, text: 'adore him,' },
  { start: 48, text: 'O come let us' },
  { start: 51, text: 'adore him,' },
  { start: 53, text: 'Christ the Lord.' },
  { start: 59, text: 'Sing, choirs of' },
  { start: 63, text: 'angels, sing in' },
  { start: 65, text: 'exultation;' },
  { start: 67, text: 'O sing, all ye' },
  { start: 72, text: 'citizens of heaven' },
  { start: 75, text: 'above!' },
  { start: 77, text: 'Glory to God, all' },
  { start: 82, text: 'glory in the highest;' },
  { start: 86, text: 'O come let us' },
  { start: 89, text: 'adore him,' },
  { start: 91, text: 'O come let us' },
  { start: 93, text: 'adore him,' },
  { start: 95, text: 'O come let us' },
  { start: 98, text: 'adore him,' },
  { start: 101, text: 'Christ the Lord.' },
  { start: 106, text: 'Yea, Lord, we' },
  { start: 110, text: 'greet thee, born' },
  { start: 113, text: 'this happy morning,' },
  { start: 115, text: 'Jesus, to thee be' },
  { start: 120, text: 'all the glory given.' },
  { start: 124, text: 'Word of the Father,' },
  { start: 129, text: 'now in flesh' },
  { start: 131, text: 'appearing' },
  { start: 133, text: 'O come let us' },
  { start: 136, text: 'adore him,' },
  { start: 138, text: 'O come let us' },
  { start: 141, text: 'adore him,' },
  { start: 143, text: 'O come let us' },
  { start: 146, text: 'adore him,' },
  { start: 148, text: 'Christ the Lord.' }
];

export default lyrics;